name: main-build

on:
  push:
    branches:
      - master

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.do_stuff.outputs.result1 }}
    steps:
    - uses: actions/checkout@v3
    - id: do_stuff
      name: do stuff
      run: echo "::set-output name=result1::hello"

  job2:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.do_stuff2.outputs.result2 }}
      output2: ''
    steps:
    - uses: actions/checkout@v3
    - id: do_stuff2
      name: do stuff2
      run: bash ./ci/do-something.sh

  unify:
    runs-on: ubuntu-latest
    needs: [job1,job2]
    steps:
    - name: echos
      # if: github.ref == 'refs/heads/main' && github.repository == ''
      # env:
      #   RESULT1: ${{ jobs.job1.outputs.output1 }}
      #   RESULT2: ${{ jobs.job2.outputs.output1 }}
      run: |
        echo J1 ${{ needs.job1.outputs.output1 }}
        echo J2.1 ${{ needs.job2.outputs.output1 }}
        echo J2.2 ${{ needs.job2.outputs.output2 }}
        echo J2.X ${{ needs.job2.outputs.outputX }}

  auto-tag-artifact:
    runs-on: ubuntu-latest
    outputs:
      hello: ${{ steps.stepx.outputs.hello }}    
    steps:
    - uses: actions/checkout@v3
      with:
        ssh-key: ${{ secrets.DEPLOY_KEY }}
      #   repository: abapGit/build
      #   ref: fix-tagging3
    - name: mirror tag to the artifact
      id: stepx
      env:
        # GITHUB_API_KEY: 'xxxx#/abc'
        GIT_USER_NAME: 'github-actions[bot]'
        GIT_USER_EMAIL: 'github-actions[bot]@users.noreply.github.com'
      run: |
        ls -RAFl
        ./ci/push-tag.sh v123
      # run: |
      #   echo "hello=world" >> $GITHUB_OUTPUT
    # - name: read var
    #   run: echo "${{ steps.stepx.outputs.hello }}"        
  
  test-needs:
    runs-on: ubuntu-latest
    needs: ['auto-tag-artifact']
    steps:
    - name: test needs
      run: |
        echo pre ${{ needs.auto-tag-artifact.outputs.hello }}
        echo -e full "${{ toJSON(needs.auto-tag-artifact) }}"

  multi-clone:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        repository: abapGit/build
        path: build
    - uses: actions/checkout@v3
      with:
        repository: abapGit/abapGit
        path: abapGit
    - name: mirror tag to the artifact
      env:
        GITHUB_API_KEY: 'xxxx_abc'
        GIT_USER_NAME: 'github-actions[bot]'
        GIT_USER_EMAIL: 'github-actions[bot]@users.noreply.github.com'
      # run: |
      #   ./ci/push-tag.sh 123
      run: |
        ls -AFl
        cd abapGit
        ../build/ci/push-tag.sh 123
